export const EQUITY_ANALYST_SECTIONS = [
  "What is this security?",
  "What does the company do and how does it get paid?",
  "How did it get here?",
  "Who pays them and how concentrated is it?",
  "What do they sell and what is the mix trend?",
  "What outside force moves the stock?",
  "Financial history",
  "Does reported profit turn into cash?",
  "What can break the balance sheet?",
  "Who runs it and do incentives match shareholders?",
  "What did they promise and what happened?",
  "What drives growth for the next 2–3 years?",
  "What could go better than base case?",
  "What could go worse than base case?",
  "Valuation: bear, base, bull",
  "Catalysts to watch",
  "Verdict and triggers (upgrade / downgrade)",
  "What we do not know (gaps)",
] as const;
