import type { CatalogArticleMeta } from "./types";

export const deepCatalogMeta: CatalogArticleMeta[] = [
  {
    slug: "fact-midcap-memo",
    title: "FACT: regulated fertilizer margins at a commodity-cycle trough",
    dek: "Phosphoric acid broke Factamfos in FY25; ₹735 prices in a recovery the base case does not yet see.",
    verdict: "avoid",
    conviction: "high",
    keyTakeaways: [
      "FY25 consolidated OPM fell to about 2.3% while interest stayed near ₹246 crore.",
      "Factamfos production dropped to 644,768 MT; ammonium sulphate hit a record.",
      "Base FY27 PAT × P/E implies about ₹51 per share vs ₹735 reference (-93%).",
      "Borrowings spiked to ₹3,837 crore by Sep 2025; restructuring remains pending.",
    ],
    readMinutes: 22,
    publishedAt: "2026-10-04",
    symbol: "FACT",
  },
  {
    slug: "chambalfert-midcap-memo",
    title: "Chambal: urea efficiency, P&K trading, and TAN optionality at a cyclical multiple",
    dek: "FY25 PAT rose 24% while the stock sits near 52-week lows; base FY27E PAT × P/E implies ~₹474 vs ₹399 reference.",
    verdict: "buy",
    conviction: "medium",
    keyTakeaways: [
      "FY25 urea production 34.62 lakh MT with CPC-SN revenue ₹926 crore (+22% YoY).",
      "Borrowings fell to ₹99 crore at Mar 2025; TAN capex ₹1,052 crore spent by Sep 2025.",
      "Base FY27 PAT ₹1,900 cr × 10× P/E implies ~₹474 (+19% vs ₹399 reference).",
      "Risk: Gadepan-III shutdowns and DAP price spikes compress traded fertiliser spreads.",
    ],
    readMinutes: 24,
    publishedAt: "2026-10-04",
    symbol: "CHAMBLFERT",
  },
  {
    slug: "coromandel-midcap-memo",
    title: "Coromandel: phosphatic integration and crop protection at a full multiple",
    dek: "Kakinada acid plants and NACL expand the moat; at ₹1,764 base FY27E offers ~8% upside, not yet a Buy.",
    verdict: "neutral",
    conviction: "medium",
    keyTakeaways: [
      "TTM revenue near ₹31,479 cr on higher urea trading and NPK volume.",
      "Kakinada sulphuric and phosphoric acid plants commissioned Q4 FY26 (₹1,100 cr).",
      "Base FY27 PAT ₹2,550 cr × 22× P/E implies ~₹1,902 vs ₹1,764 reference (+8%).",
      "Borrowings rose to ₹1,506 cr Mar FY26 on capex and NACL acquisition.",
    ],
    readMinutes: 25,
    publishedAt: "2026-10-04",
    symbol: "COROMANDEL",
  },
  {
    slug: "deepakfert-midcap-memo",
    title: "Deepak Fertilisers: integrated TAN, IPA, and Mahadhan at a capex crossroads",
    dek: "Jun 2026 margin spike flattered TTM earnings; at ₹1,301 base FY27E offers ~9% upside, not yet a Buy.",
    verdict: "neutral",
    conviction: "medium",
    keyTakeaways: [
      "TTM revenue near ₹12,104 cr; Jun 2026 quarter PAT ₹490 cr drove trailing multiples.",
      "Borrowings ₹5,670 cr and CWIP ₹3,053 cr Mar FY26 on Dahej expansion.",
      "Base FY27 PAT ₹1,050 cr × 17× P/E implies ~₹1,415 vs ₹1,301 reference (+9%).",
      "FY26 CFO only ₹206 cr; free cash flow negative ₹1,363 cr on Screener.",
    ],
    readMinutes: 24,
    publishedAt: "2026-10-04",
    symbol: "DEEPAKFERT",
  },
  {
    slug: "gnfc-midcap-memo",
    title: "GNFC: Bharuch chemicals recovery and urea policy at a single-digit multiple",
    dek: "TTM PAT rebounded on TDI and nitric acid spreads; at ₹589 base FY27E offers ~8% upside, not yet a Buy.",
    verdict: "neutral",
    conviction: "medium",
    keyTakeaways: [
      "TTM revenue near ₹8,410 cr; Mar and Jun 2026 quarters drove trailing PAT ₹1,037 cr.",
      "Borrowings ₹5 cr and CWIP ₹900 cr Mar FY26 ahead of ₹2,800 cr FY27 capex wave.",
      "Base FY27 PAT ₹980 cr × 9.5× P/E implies ~₹633 vs ₹589 reference (+7.5%).",
      "Urea fixed-cost reimbursement and working capital days at 157 remain policy and WC risks.",
    ],
    readMinutes: 24,
    publishedAt: "2026-10-04",
    symbol: "GNFC",
  },
  {
    slug: "gsfc-midcap-memo",
    title: "GSFC: caprolactam cycle and PSU dividend yield at book discount",
    dek: "TTM PAT held near ₹693 cr on treasury-backed other income; at ₹147 base FY27E offers ~1% upside, not yet a Buy.",
    verdict: "neutral",
    conviction: "medium",
    keyTakeaways: [
      "TTM revenue near ₹12,344 cr; Sep 2025 quarter PAT ₹324 cr vs Mar 2026 ₹52 cr.",
      "Borrowings ₹27 cr and investments ₹4,610 cr Mar FY26; CWIP rolled to fixed assets ₹3,331 cr.",
      "Base FY27 PAT ₹700 cr × 8.5× P/E implies ~₹149 vs ₹147 reference (+1.4%).",
      "Working capital days at 154 and FY26 CFO ₹136 cr remain conversion risks.",
    ],
    readMinutes: 24,
    publishedAt: "2026-10-04",
    symbol: "GSFC",
  },
  {
    slug: "rcf-midcap-memo",
    title: "RCF: Trombay-Thal urea and industrial chemicals at a reimbursement crossroads",
    dek: "TTM PAT rebounded on Mar 2026 quarter strength; at ₹107 base FY27E offers ~6% upside, not yet a Buy.",
    verdict: "neutral",
    conviction: "medium",
    keyTakeaways: [
      "TTM revenue near ₹18,695 cr; Mar 2026 quarter PAT ₹187 cr vs Jun 2026 ₹74 cr.",
      "Borrowings ₹4,128 cr and CWIP ₹810 cr Mar FY26; FY26 CFO negative ₹471 cr.",
      "Base FY27 PAT ₹500 cr × 12.5× P/E implies ~₹113 vs ₹107 reference (+5.6%).",
      "Interest TTM near ₹308 cr; reimbursement timing remains the key fertiliser swing.",
    ],
    readMinutes: 24,
    publishedAt: "2026-10-04",
    symbol: "RCF",
  },
  {
    slug: "paradeep-midcap-memo",
    title: "Paradeep Phosphates: OCP-backed integration at a leverage crossroads",
    dek: "TTM PAT crossed ₹1,000 cr on acid debottlenecking; at ₹151 base FY27E offers ~5% downside, not yet a Buy.",
    verdict: "neutral",
    conviction: "medium",
    keyTakeaways: [
      "TTM revenue near ₹23,447 cr; Jun 2026 quarter PAT ₹393 cr drove trailing multiples.",
      "Borrowings ₹6,906 cr and FY26 CFO negative ₹1,012 cr on subsidy WC.",
      "Base FY27 PAT ₹1,100 cr × 13.5× P/E implies ~₹143 vs ₹151 reference (-5.3%).",
      "700 KTPA phosphoric acid and sulphuric expansion are the key FY27 margin levers.",
    ],
    readMinutes: 25,
    publishedAt: "2026-10-04",
    symbol: "PARADEEP",
  },
  {
    slug: "mangalorechem-midcap-memo",
    title: "Mangalore Chemicals: west-coast urea and Paradeep merger optionality at a full multiple",
    dek: "Q1 FY26 PAT rebounded but trailing P/E embeds integration hope; at ₹309 base FY27E offers ~38% downside, not a Buy.",
    verdict: "neutral",
    conviction: "medium",
    keyTakeaways: [
      "FY25 urea production 443,322 MT exceeded reassessed capacity per BSE annual report.",
      "Q1 FY26 revenue ₹862 cr and PAT ₹62 cr per investor deck; borrowings trended lower.",
      "Base FY27 PAT ₹175 cr × 13× P/E implies ~₹192 vs ₹309 reference (-38%).",
      "Paradeep amalgamation cleared CCI but was not closed by Oct 2026 reference.",
    ],
    readMinutes: 25,
    publishedAt: "2026-10-04",
    symbol: "MANGCHEFER",
  },
  {
    slug: "nfl-midcap-memo",
    title: "National Fertilizers: Navratna urea scale at a reimbursement crossroads",
    dek: "TTM PAT rebounded on seasonal quarters but FY26 CFO was negative; at ₹63.8 base FY27E offers ~7% downside, not yet a Buy.",
    verdict: "neutral",
    conviction: "medium",
    keyTakeaways: [
      "FY25 turnover ₹19,795 cr and PAT ₹76 cr per BSE annual report; TTM PAT ₹273 cr on Screener.",
      "Borrowings ₹3,964 cr Mar FY26; debtor days 92; FY26 CFO negative ₹1,384 cr.",
      "Base FY27 PAT ₹265 cr × 11× P/E implies ~₹59 vs ₹63.8 reference (-7%).",
      "Ramagundam Fertilizers JV and traded volumes are the main FY27 swing factors.",
    ],
    readMinutes: 25,
    publishedAt: "2026-10-04",
    symbol: "NFL",
  },
  {
    slug: "zuariind-midcap-memo",
    title: "Zuari Industries: Adventz holding discount versus fertilizer NAV",
    dek: "Quoted stakes exceed market cap but FY26 PAT is lumpy; at ₹282 base FY27E offers ~7% downside, not yet a Buy.",
    verdict: "neutral",
    conviction: "medium",
    keyTakeaways: [
      "Q4 FY25 deck: quoted strategic investments ₹4,701 cr; Chambal stake ₹3,177 cr at 31 Mar 2025.",
      "Consolidated borrowings ₹2,657 cr Mar FY26; TTM interest ₹241 cr; investments ₹4,851 cr on Screener.",
      "Base FY27 PAT ₹92 cr × 8.5× P/E implies ~₹261 vs ₹282 reference (-7%).",
      "Paradeep via ZMPPL and Mangalore amalgamation drive group optionality, not consolidated PAT.",
    ],
    readMinutes: 25,
    publishedAt: "2026-10-04",
    symbol: "ZUARIIND",
  },
  {
    slug: "zuariagro-midcap-memo",
    title: "Zuari Agro Chemicals: Paradeep stake marks at a holding company discount",
    dek: "Sep 2025 fair value drove TTM PAT; at ₹213 base FY27E offers ~7% downside, not yet a Buy.",
    verdict: "neutral",
    conviction: "medium",
    keyTakeaways: [
      "Investments ₹2,581 cr Mar FY26 vs MCap ₹895 cr; book ₹497/sh (0.43× on Screener).",
      "Sep 2025 quarter PAT ₹840 cr on other income ₹923 cr; normalize FY27 toward ₹145 cr PAT.",
      "Borrowings ₹642 cr Mar FY26; contingent liabilities ₹374 cr; promoter pledge 27.6%.",
      "Base FY27 PAT ₹145 cr × 5.75× P/E implies ~₹198 vs ₹213 reference (-7%).",
    ],
    readMinutes: 25,
    publishedAt: "2026-10-04",
    symbol: "ZUARI",
  },
  {
    slug: "piind-midcap-memo",
    title: "PI Industries: CSM export cycle and domestic agri-inputs at a de-rated multiple",
    dek: "FY26 sales fell but OPM held near 32%; at ₹2,236 base FY27E offers ~2% downside, not yet a Buy.",
    verdict: "neutral",
    conviction: "medium",
    keyTakeaways: [
      "FY25 peak PAT ₹1,866 cr on sales ₹7,571 cr; FY26 PAT ₹1,435 cr on sales ₹6,183 cr (Screener).",
      "Debtor days 80 and WC days 120 Mar FY26; FY26 CFO ₹694 cr versus OP ₹1,962 cr.",
      "CWIP ₹875 cr Mar FY26; borrowings ₹65 cr; almost debt free balance sheet.",
      "Base FY27 PAT ₹1,520 cr × 22× P/E implies ~₹2,198 vs ₹2,236 reference (-2%).",
    ],
    readMinutes: 25,
    publishedAt: "2026-10-04",
    symbol: "PIIND",
  },
  {
    slug: "upl-midcap-memo",
    title: "UPL: global crop protection recovery at a premium multiple",
    dek: "FY26 CFO was negative ₹2,243 cr but OPM rebounded on TTM; at ₹517 base FY27E offers ~8% downside, not yet a Buy.",
    verdict: "neutral",
    conviction: "medium",
    keyTakeaways: [
      "FY25 PAT ₹2,939 cr included other income ₹2,552 cr; FY26 PAT ₹785 cr on OP ₹422 cr (Screener).",
      "Debtor days 210 and WC days 289 Mar FY26; three years of negative CFO.",
      "Borrowings ₹869 cr vs investments ₹5,967 cr Mar FY26; almost debt free on Screener pros.",
      "Base FY27 PAT ₹1,180 cr × 34× P/E implies ~₹475 vs ₹517 reference (-8%).",
    ],
    readMinutes: 25,
    publishedAt: "2026-10-04",
    symbol: "UPL",
  },
  {
    slug: "rallis-midcap-memo",
    title: "Rallis: Tata crop care and seeds recovery at a modest ROE multiple",
    dek: "FY26 EBITDA hit a record ₹362 cr but net CFO eased; at ₹200 base FY27E offers ~8% upside, not yet a Buy.",
    verdict: "neutral",
    conviction: "medium",
    keyTakeaways: [
      "FY26 revenue ₹2,897 cr (+9%); PAT ₹184 cr (+47%); EBITDA margin 12.5%.",
      "Seeds ₹481 cr (+15%); crop care ₹2,416 cr (+8%) per FY26 concall.",
      "Net CFO ₹172 cr FY26; liquid balances ~₹541 cr Mar FY26 vs borrowings ~₹93 cr.",
      "Base FY27 PAT ₹200 cr × 21× P/E implies ~₹216 vs ₹200 reference (+8%).",
    ],
    readMinutes: 24,
    publishedAt: "2026-10-04",
    symbol: "RALLIS",
  },
  {
    slug: "dhanuka-midcap-memo",
    title: "Dhanuka Agritech: 9(3) mix and high ROCE at a de-rated agchem multiple",
    dek: "FY26 revenue paused but OPM held near 20%; at ₹935 base FY27E offers ~15% upside to a Buy.",
    verdict: "buy",
    conviction: "medium",
    keyTakeaways: [
      "FY26 revenue ~₹2,020 cr; PAT ~₹287 cr; OPM near 20%; ROCE 28.3%.",
      "Q2 FY26 mix: insecticides 46%, fungicides 29%, herbicides 9%.",
      "Net CFO ~₹240 cr FY26; almost debt free on Screener.",
      "Base FY27 PAT ₹300 cr × 16× P/E implies ~₹1,076 vs ₹935 reference (+15%).",
    ],
    readMinutes: 24,
    publishedAt: "2026-10-04",
    symbol: "DHANUKA",
  },
  {
    slug: "insecticides-midcap-memo",
    title: "Insecticides India: Maharatna mix at a cyclical agchem multiple",
    dek: "FY26 revenue crossed ₹2,140 cr but Q1 FY27 volume softened; at ₹569 base FY27E offers ~18% upside to a Buy.",
    verdict: "buy",
    conviction: "medium",
    keyTakeaways: [
      "FY26 revenue ~₹2,140 cr; PAT ~₹139 cr; EBITDA margin ~10.6%; ROCE 15.8%.",
      "Q1 FY27 revenue -12% YoY; gross margin held near 32% per investor deck.",
      "Net CFO ~₹145 cr FY26; moderate leverage on Screener.",
      "Base FY27 PAT ₹150 cr × 13× P/E implies ~₹670 vs ₹569 reference (+18%).",
    ],
    readMinutes: 24,
    publishedAt: "2026-10-04",
    symbol: "INSECTICID",
  },
  {
    slug: "sumichem-midcap-memo",
    title: "Sumitomo Chemical India: SCC specialty mix at a full agchem multiple",
    dek: "FY26 OPM held near 21% but five-year sales CAGR is ~4%; at ₹418 base FY27E offers ~11% upside, not yet a Buy.",
    verdict: "neutral",
    conviction: "medium",
    keyTakeaways: [
      "FY26 revenue ~₹3,238 cr; PAT ~₹543 cr; OPM ~21%; ROCE 22.1%.",
      "Almost debt free; investments ~₹1,153 cr Mar FY26 on Screener.",
      "Net CFO ~₹446 cr FY26; working capital cycle remains long.",
      "Base FY27 PAT ₹640 cr × 36× P/E implies ~₹462 vs ₹418 reference (+11%).",
    ],
    readMinutes: 24,
    publishedAt: "2026-10-04",
    symbol: "SUMICHEM",
  },
  {
    slug: "shardacrop-midcap-memo",
    title: "Sharda Cropchem: registration moat at a cyclical export multiple",
    dek: "FY26 PAT rebounded to ₹681 cr but debtor days stay near 166; at ₹709 base FY27E offers ~12% upside, not yet a Buy.",
    verdict: "neutral",
    conviction: "medium",
    keyTakeaways: [
      "FY26 revenue ~₹5,268 cr; PAT ~₹681 cr; OPM ~20%; ROCE 30.2%.",
      "Q1 FY27 revenue +9% YoY; gross margin 36.7% per Jul 2026 call.",
      "Debt free; cash and liquid investments ~₹767 cr Jun 2026.",
      "Base FY27 PAT ₹650 cr × 11× P/E implies ~₹792 vs ₹709 reference (+12%).",
    ],
    readMinutes: 24,
    publishedAt: "2026-10-04",
    symbol: "SHARDACROP",
  },
  {
    slug: "meghmani-midcap-memo",
    title: "Meghmani Organics: crop protection recovery with pigment and Brazil optionality",
    dek: "FY26 EBITDA rose 27% but Q1 FY27 revenue fell 12%; at ₹73 base FY27E offers ~11% upside, not yet a Buy.",
    verdict: "neutral",
    conviction: "medium",
    keyTakeaways: [
      "FY26 revenue ~₹2,092 cr; PAT ~₹105 cr; EBITDA margin ~17.3%; ROCE ~11%.",
      "Q1 FY27 revenue ~₹523 cr (-12% YoY); EBITDA margin 17.9% per investor deck.",
      "Borrowings ~₹182 cr Mar FY26; amalgamation and Brazil setup in progress.",
      "Base FY27 PAT ₹130 cr × 15× P/E implies ~₹81 vs ₹73 reference (+11%).",
    ],
    readMinutes: 24,
    publishedAt: "2026-10-04",
    symbol: "MOL",
  },
  {
    slug: "bharatras-midcap-memo",
    title: "Bharat Rasayan: technical export cycle at a deep de-rating",
    dek: "FY26 OPM recovered to 16% after FY24 shock; at ₹999 base FY27E offers ~18% upside to a Buy.",
    verdict: "buy",
    conviction: "medium",
    keyTakeaways: [
      "FY26 revenue ₹1,240 cr; PAT ₹146 cr; OPM 16%; ROCE 16%.",
      "Top ten products ~66% of sales; almost debt free Mar FY26.",
      "Net CFO ₹132 cr FY26; working capital days near 192.",
      "Base FY27 PAT ₹170 cr × 11.5× P/E implies ~₹1,178 vs ₹999 reference (+18%).",
    ],
    readMinutes: 25,
    publishedAt: "2026-10-04",
    symbol: "BHARATRAS",
  },
  {
    slug: "astec-midcap-memo",
    title: "Astec LifeSciences: leveraged agchem turnaround priced ahead of base recovery",
    dek: "FY26 revenue rebounded but PAT loss near ₹81 cr; at ₹709 base FY27E implies ~85% downside, Avoid.",
    verdict: "avoid",
    conviction: "medium",
    keyTakeaways: [
      "FY26 revenue ₹448 cr; PAT -₹81 cr; OPM near breakeven; ROCE -5%.",
      "Borrowings ₹449 cr Mar FY26; debtor days 202; FY26 net CFO -₹81 cr.",
      "Promoter ~72% Jun 2026; Q1 FY27 still loss-making.",
      "Base FY27 PAT ₹22 cr × 11× P/E implies ~₹109 vs ₹709 reference (-85%).",
    ],
    readMinutes: 25,
    publishedAt: "2026-10-04",
    symbol: "ASTEC",
  },
  {
    slug: "heranba-midcap-memo",
    title: "Heranba Industries: export agchem recovery after two loss years",
    dek: "Q1 FY27 OPM near 14% but TTM PAT still negative; at ₹172 base FY27E offers ~9% downside, not yet a Buy.",
    verdict: "neutral",
    conviction: "medium",
    keyTakeaways: [
      "FY26 TTM revenue ₹1,526 cr; PAT -₹77 cr; OPM 6%; ROCE negative.",
      "Q1 FY27 revenue ₹437 cr; OPM 13.6%; FY25 CFO -₹96 cr.",
      "Book ~₹202/sh; MCap ₹689 cr on 4.01 cr shares.",
      "Base FY27 PAT ₹52 cr × 12× P/E implies ~₹156 vs ₹172 reference (-9%).",
    ],
    readMinutes: 25,
    publishedAt: "2026-10-04",
    symbol: "HERANBA",
  },
  {
    slug: "indofil-midcap-memo",
    title: "Indofil Industries: mancozeb integration at an unlisted discount",
    dek: "OTC reference ₹1,475 vs book ~₹2,831; base FY27E offers ~6% upside, Neutral on illiquidity.",
    verdict: "neutral",
    conviction: "medium",
    keyTakeaways: [
      "Unlisted ISIN INE071I01016; OTC ref ₹1,475 (2 Oct 2026), not exchange CMP.",
      "Estimated FY26 revenue ~₹4,620 cr; PAT ~₹452 cr; OPM ~11% (model until DRHP).",
      "Dealer book ~₹2,831/sh; ROE ~7%; mancozeb-led export agchem plus specialty chemicals.",
      "Base FY27 PAT ₹480 cr × 7.5× P/E implies ~₹1,567 vs ₹1,475 reference (+6%).",
    ],
    readMinutes: 25,
    publishedAt: "2026-10-04",
    symbol: "INDOFIL",
  },
  {
    slug: "naclind-midcap-memo",
    title: "NACL Industries: Coromandel control at a triple-digit earnings multiple",
    dek: "FY26 OP recovered but PAT was ₹5 cr; at ₹130 base FY27E implies ~70% downside, Avoid.",
    verdict: "avoid",
    conviction: "medium",
    keyTakeaways: [
      "Coromandel promoter ~53.7% from Aug 2025; open offer ₹76.70 vs CMP ₹130.",
      "FY26 revenue ₹1,584 cr; OP ₹103 cr; PAT ₹5 cr; FY26 CFO -₹104 cr.",
      "Q1 FY27 revenue ₹383 cr; OPM 11%; PAT ₹21 cr.",
      "Base FY27 PAT ₹65 cr × 14× P/E implies ~₹39 vs ₹130 reference (-70%).",
    ],
    readMinutes: 25,
    publishedAt: "2026-10-04",
    symbol: "NACLIND",
  },
  {
    slug: "kaveri-midcap-memo",
    title: "Kaveri Seed: non-cotton hybrid mix at a de-rated seed multiple",
    dek: "FY26 revenue rose 16% but FY26 CFO was negative; at ₹715 base FY27E offers ~16% upside to a Buy.",
    verdict: "buy",
    conviction: "medium",
    keyTakeaways: [
      "FY26 revenue ₹1,392 cr; PAT ₹296 cr; non-cotton mix ~82%; OPM 24%.",
      "Q1 FY27 revenue ₹742 cr (-9% YoY); maize volumes -39%; OPM 40% seasonal.",
      "FY26 net CFO -₹6 cr; WC days 171; almost debt free.",
      "Base FY27 PAT ₹305 cr × 14× P/E implies ~₹831 vs ₹715 reference (+16%).",
    ],
    readMinutes: 25,
    publishedAt: "2026-10-04",
    symbol: "KSCL",
  },
  {
    slug: "nathbiogen-midcap-memo",
    title: "Nath Bio-Genes: hybrid seed scale-up at a book-discount multiple",
    dek: "FY26 sales jumped 66% but OPM fell to 12% and FY26 CFO was negative; at ₹138 base FY27E offers ~17% upside to a Buy.",
    verdict: "buy",
    conviction: "medium",
    keyTakeaways: [
      "FY26 revenue ₹445 cr (+66% YoY); PAT ₹42 cr; OPM 12%; borrowings ₹138 cr.",
      "FY26 net CFO -₹13 cr; contingent liabilities ₹89.3 cr; ROCE ~7%.",
      "Q1 FY27 revenue ₹328 cr; OPM ~11%; PAT ₹32 cr (seasonal June quarter).",
      "Base FY27 PAT ₹41 cr × 7.5× P/E implies ~₹162 vs ₹138 reference (+17%).",
    ],
    readMinutes: 24,
    publishedAt: "2026-10-04",
    symbol: "NATHBIOGEN",
  },
  {
    slug: "aries-midcap-memo",
    title: "Aries Agro: micronutrient bookings at a mid-teens multiple",
    dek: "FY26 TTM revenue near ₹779 cr; at ₹477 base FY27E offers ~16% upside to a Buy on booking conversion.",
    verdict: "buy",
    conviction: "medium",
    keyTakeaways: [
      "FY26 revenue ₹740 cr; PAT ₹42 cr; OPM 10%; ROCE 21%.",
      "FY26 dealer bookings ₹830 cr for gross revenue target near ₹950 cr.",
      "FY26 CFO ₹86 cr; working capital days 60; borrowings ₹56 cr.",
      "Base FY27 PAT ₹52 cr × 13.5× P/E implies ~₹551 vs ₹477 reference (+16%).",
    ],
    readMinutes: 25,
    publishedAt: "2026-10-04",
    symbol: "ARIES",
  },
  {
    slug: "bhagchem-midcap-memo",
    title: "Bhagiradha Chemicals: capex recovery priced at triple-digit earnings",
    dek: "TTM PAT rebounded but ROCE is 5% and borrowings ₹235 cr; at ₹236 base FY27E implies ~73% downside, Avoid.",
    verdict: "avoid",
    conviction: "medium",
    keyTakeaways: [
      "FY26 revenue ₹536 cr; TTM sales ₹607 cr; OPM 11%; ROCE 5%.",
      "FY26 borrowings ₹235 cr; TTM interest ₹21 cr; FY26 CFO ₹12 cr.",
      "Q1 FY27 revenue ₹195 cr; OPM 16%; PAT ₹13 cr (Jun 2026 quarter).",
      "Base FY27 PAT ₹38 cr × 22× P/E implies ~₹64 vs ₹236 reference (-73%).",
    ],
    readMinutes: 25,
    publishedAt: "2026-10-04",
    symbol: "BHAGCHEM",
  },
  {
    slug: "bestagro-midcap-memo",
    title: "Best Agrolife: integrated technical recovery below book value",
    dek: "Q1 FY27 OPM near 20% after FY26 PAT trough; at ₹17.5 base FY27E offers ~24% upside to a Buy.",
    verdict: "buy",
    conviction: "medium",
    keyTakeaways: [
      "FY26 revenue ₹1,257 cr; PAT ₹9 cr; book ~₹21.7/sh; ROCE 5%.",
      "Q1 FY27 revenue ₹396 cr; OPM 20%; borrowings ₹442 cr Mar FY26.",
      "FY26 net CFO ₹97 cr; debtor days 142; ~35 cr shares.",
      "Base FY27 PAT ₹42 cr × 18× P/E implies ~₹22 vs ₹17.5 reference (+24%).",
    ],
    readMinutes: 25,
    publishedAt: "2026-10-04",
    symbol: "BESTAGRO",
  },
  {
    slug: "hikal-midcap-memo",
    title: "Hikal: crop protection and pharma CDMO at an earnings trough",
    dek: "FY26 PAT loss near ₹49 cr despite ₹302 cr CFO; at ₹218 base FY27E implies ~55% downside, Avoid.",
    verdict: "avoid",
    conviction: "medium",
    keyTakeaways: [
      "FY26 revenue ₹1,713 cr; PAT -₹49 cr; OPM 13%; ROCE 4%.",
      "FY26 net CFO ₹302 cr; borrowings ₹684 cr; TTM PAT -₹34 cr.",
      "Q1 FY27 revenue ₹403 cr; OPM 9%; PAT -₹7.5 cr (Jun 2026 quarter).",
      "Base FY27 PAT ₹68 cr × 18× P/E implies ~₹98 vs ₹218 reference (-55%).",
    ],
    readMinutes: 25,
    publishedAt: "2026-10-04",
    symbol: "HIKAL",
  },
  {
    slug: "bhageria-midcap-memo",
    title: "Bhageria Industries: dyes and agchem ramp at a full multiple",
    dek: "TTM revenue near ₹1,003 cr; at ₹382 base FY27E offers ~11% upside, not yet a Buy.",
    verdict: "neutral",
    conviction: "medium",
    keyTakeaways: [
      "FY26 revenue ₹874 cr; PAT ₹44 cr; OPM 10%; ROCE 9%.",
      "FY26 net CFO ₹99 cr; borrowings ₹109 cr; CWIP ₹117 cr.",
      "Q1 FY27 revenue ₹286 cr; OPM 15%; PAT ₹34 cr (Jun 2026 quarter).",
      "Base FY27 PAT ₹84 cr × 22× P/E implies ~₹423 vs ₹382 reference (+11%).",
    ],
    readMinutes: 25,
    publishedAt: "2026-10-04",
    symbol: "BHAGERIA",
  },
  {
    slug: "rossari-midcap-memo",
    title: "Rossari Biotech: HPPC scale-up at a de-rated specialty chemicals multiple",
    dek: "TTM revenue near ₹2,550 cr; at ₹428 base FY27E offers ~18% upside to a Buy on utilisation ramp.",
    verdict: "buy",
    conviction: "medium",
    keyTakeaways: [
      "FY26 revenue ₹2,396 cr; PAT ₹149 cr; OPM 12%; ROCE 13%.",
      "FY26 net CFO ₹65 cr; borrowings ₹436 cr; CWIP ₹173 cr.",
      "Q1 FY27 revenue ₹697 cr; OPM 12%; PAT ₹35 cr (Jun 2026 quarter).",
      "Base FY27 PAT ₹175 cr × 16× P/E implies ~₹506 vs ₹428 reference (+18%).",
    ],
    readMinutes: 25,
    publishedAt: "2026-10-04",
    symbol: "ROSSARI",
  },
  {
    slug: "fineorg-midcap-memo",
    title: "Fine Organic: oleochemical additives at a premium multiple",
    dek: "TTM revenue near ₹2,472 cr; at ₹5,131 base FY27E offers ~8% upside, not yet a Buy.",
    verdict: "neutral",
    conviction: "medium",
    keyTakeaways: [
      "FY26 revenue ₹2,366 cr; PAT ₹417 cr; OPM 20%; ROCE 21%.",
      "FY26 net CFO ₹430 cr; borrowings ₹68 cr; CWIP ₹64 cr.",
      "Q1 FY27 revenue ₹694 cr; OPM 25%; PAT ₹138 cr (Jun 2026 quarter).",
      "Base FY27 PAT ₹500 cr × 34× P/E implies ~₹5,547 vs ₹5,131 reference (+8%).",
    ],
    readMinutes: 25,
    publishedAt: "2026-10-04",
    symbol: "FINEORG",
  },
  {
    slug: "galaxysurf-midcap-memo",
    title: "Galaxy Surfactants: oleo surfactants recovery at a mid-cycle multiple",
    dek: "TTM revenue near ₹5,752 cr; at ₹2,377 base FY27E offers ~19% upside to a Buy on margin normalisation.",
    verdict: "buy",
    conviction: "medium",
    keyTakeaways: [
      "FY26 revenue ₹5,245 cr; PAT ₹267 cr; OPM 9%; ROCE 14%.",
      "FY26 net CFO ₹333 cr; borrowings ₹235 cr; investments ₹474 cr.",
      "Q1 FY27 revenue ₹1,782 cr; OPM 14%; PAT ₹166 cr (Jun 2026 quarter).",
      "Base FY27 PAT ₹455 cr × 22× P/E implies ~₹2,820 vs ₹2,377 reference (+19%).",
    ],
    readMinutes: 25,
    publishedAt: "2026-10-04",
    symbol: "GALAXYSURF",
  },
  {
    slug: "vinatiorga-midcap-memo",
    title: "Vinati Organics: IBB and ATBS niches at a de-rated specialty multiple",
    dek: "TTM revenue near ₹2,381 cr; at ₹1,208 base FY27E offers ~20% upside to a Buy on margin and ATBS mix.",
    verdict: "buy",
    conviction: "medium",
    keyTakeaways: [
      "FY26 revenue ₹2,227 cr; PAT ₹444 cr; OPM 29%; ROCE 20%.",
      "FY26 net CFO ₹558 cr; borrowings ₹6 cr; CWIP ₹214 cr.",
      "Q1 FY27 revenue ₹696 cr; OPM 24% (Jun 2026 quarter).",
      "Base FY27 PAT ₹500 cr × 30× P/E implies ~₹1,446 vs ₹1,208 reference (+20%).",
    ],
    readMinutes: 25,
    publishedAt: "2026-10-04",
    symbol: "VINATIORGA",
  },
  {
    slug: "cleansci-midcap-memo",
    title: "Clean Science: HALS moat and Performance Chemical ramp at a de-rated multiple",
    dek: "TTM revenue near ₹982 cr; at ₹803 base FY27E offers ~16% upside to a Buy on margin and HALS run-rate.",
    verdict: "buy",
    conviction: "medium",
    keyTakeaways: [
      "FY26 revenue ₹957 cr; PAT ₹230 cr; OPM 37%; ROCE 21%.",
      "FY26 net CFO ₹278 cr; borrowings zero; capex on Clean Fino Chem.",
      "Q1 FY27 revenue ₹268 cr; OPM 36%; PAT ₹73 cr (Jun 2026 quarter).",
      "Base FY27 PAT ₹320 cr × 31× P/E implies ~₹933 vs ₹803 reference (+16%).",
    ],
    readMinutes: 25,
    publishedAt: "2026-10-04",
    symbol: "CLEAN",
  },
  {
    slug: "deepaknit-midcap-memo",
    title: "Deepak Nitrite: phenolics cycle trough with Q1 FY27 margin rebound",
    dek: "TTM revenue near ₹8,575 cr; at ₹1,493 base FY27E offers ~17% upside to a Buy on spread recovery and capex completion.",
    verdict: "buy",
    conviction: "medium",
    keyTakeaways: [
      "FY26 revenue ₹7,887 cr; PAT ₹551 cr; OPM 13%; ROCE 11%.",
      "FY26 net CFO ₹539 cr; borrowings ₹1,638 cr; CWIP ₹1,828 cr.",
      "Q1 FY27 revenue ₹2,578 cr; OPM 21%; PAT ₹345 cr (Jun 2026 quarter).",
      "Base FY27 PAT ₹920 cr × 26× P/E implies ~₹1,755 vs ₹1,493 reference (+17%).",
    ],
    readMinutes: 25,
    publishedAt: "2026-10-04",
    symbol: "DEEPAKNTR",
  },
  {
    slug: "aartiind-midcap-memo",
    title: "Aarti Industries: benzene chain recovery at a leveraged specialty multiple",
    dek: "TTM revenue near ₹9,010 cr; at ₹465 base FY27E offers ~16% upside to a Buy on margin and PAT rebound.",
    verdict: "buy",
    conviction: "medium",
    keyTakeaways: [
      "FY26 revenue ₹8,286 cr; PAT ₹419 cr; OPM 14%; ROCE 7%.",
      "FY26 net CFO ₹781 cr; borrowings ₹4,966 cr; free cash flow negative.",
      "Q1 FY27 revenue ₹2,387 cr; OPM 16%; PAT ₹155 cr (Jun 2026 quarter).",
      "Base FY27 PAT ₹700 cr × 28× P/E implies ~₹541 vs ₹465 reference (+16%).",
    ],
    readMinutes: 25,
    publishedAt: "2026-10-04",
    symbol: "AARTIIND",
  },
  {
    slug: "atul-midcap-memo",
    title: "Atul: crop protection recovery at a diversified chemical multiple",
    dek: "TTM revenue near ₹6,643 cr; at ₹5,861 base FY27E offers ~23% upside to a Buy on margin and PAT rebound.",
    verdict: "buy",
    conviction: "medium",
    keyTakeaways: [
      "FY26 revenue ₹6,274 cr; PAT ₹689 cr; OPM 16%; ROCE 15%.",
      "FY26 net CFO ₹1,023 cr; borrowings ₹183 cr; FCF ₹851 cr.",
      "Q1 FY27 revenue ₹1,848 cr; OPM 21%; PAT ₹254 cr (Jun 2026 quarter).",
      "Base FY27 PAT ₹880 cr × 24× P/E implies ~₹7,184 vs ₹5,861 reference (+23%).",
    ],
    readMinutes: 25,
    publishedAt: "2026-10-04",
    symbol: "ATUL",
  },
  {
    slug: "srf-midcap-memo",
    title: "SRF: fluorochemical recovery at an integrated chemicals multiple",
    dek: "TTM revenue near ₹17,001 cr; at ₹2,486 base FY27E offers ~17% upside to a Buy on margin and PAT rebound.",
    verdict: "buy",
    conviction: "medium",
    keyTakeaways: [
      "FY26 revenue ₹15,787 cr; PAT ₹1,835 cr; OPM 22%; ROCE 15%.",
      "FY26 net CFO ₹2,554 cr; borrowings ₹5,083 cr; FCF ₹747 cr.",
      "Q1 FY27 revenue ₹5,033 cr; OPM 25%; PAT ₹759 cr (Jun 2026 quarter).",
      "Base FY27 PAT ₹2,650 cr × 32× P/E implies ~₹2,905 vs ₹2,486 reference (+17%).",
    ],
    readMinutes: 25,
    publishedAt: "2026-10-04",
    symbol: "SRF",
  },
  {
    slug: "navinfluor-midcap-memo",
    title: "Navin Fluorine: CDMO leverage at a premium fluorochemical multiple",
    dek: "TTM revenue near ₹3,634 cr; at ₹8,136 base FY27E offers ~8% upside, Neutral on trailing P/E near 52×.",
    verdict: "neutral",
    conviction: "medium",
    keyTakeaways: [
      "FY26 revenue ₹3,314 cr; PAT ₹664 cr; OPM 33%; ROCE 21%.",
      "FY26 net CFO ₹894 cr; borrowings ₹1,272 cr; FCF ₹404 cr.",
      "Q1 FY27 revenue ₹1,045 cr; OPM 34%; PAT ₹243 cr (Jun 2026 quarter).",
      "Base FY27 PAT ₹900 cr × 50× P/E implies ~₹8,772 vs ₹8,136 reference (+8%).",
    ],
    readMinutes: 25,
    publishedAt: "2026-10-04",
    symbol: "NAVINFLUOR",
  },
  {
    slug: "fluorochem-midcap-memo",
    title: "Gujarat Fluorochemicals: fluoropolymers priced for battery optionality",
    dek: "TTM revenue near ₹5,303 cr; at ₹4,342 base FY27E offers ~5% upside, Neutral on trailing P/E near 77× and ROCE ~9.6%.",
    verdict: "neutral",
    conviction: "medium",
    keyTakeaways: [
      "FY26 revenue ₹4,996 cr; PAT ₹574 cr; OPM 24%; ROCE ~10%.",
      "FY26 net CFO ₹961 cr; borrowings ₹2,721 cr; FCF negative on battery capex.",
      "Q1 FY27 revenue ₹1,588 cr; OPM 26%; R32 commercial from Mar 2026.",
      "Base FY27 PAT ₹650 cr × 77× P/E implies ~₹4,557 vs ₹4,342 reference (+5%).",
    ],
    readMinutes: 25,
    publishedAt: "2026-10-04",
    symbol: "FLUOROCHEM",
  },
  {
    slug: "neogen-midcap-memo",
    title: "Neogen Chemicals: battery optionality at a triple-digit earnings multiple",
    dek: "TTM revenue near ₹926 cr; at ₹2,407 base FY27E offers ~6% upside, Neutral on trailing P/E near 203× and ROCE ~6.5%.",
    verdict: "neutral",
    conviction: "medium",
    keyTakeaways: [
      "FY26 revenue ₹862 cr; PAT ₹29 cr; OPM 16%; ROCE ~6%.",
      "FY26 net CFO negative ₹231 cr; borrowings ₹1,395 cr; CWIP ₹857 cr.",
      "Q1 FY27 revenue ₹250 cr; OPM 19%; FY27 guide ₹1,250–1,350 cr consolidated.",
      "Base FY27 PAT ₹48 cr × 160× P/E implies ~₹2,560 vs ₹2,407 reference (+6%).",
    ],
    readMinutes: 25,
    publishedAt: "2026-10-04",
    symbol: "NEOGEN",
  },
  {
    slug: "anupam-midcap-memo",
    title: "Anupam Rasayan: life-science growth at a leveraged specialty multiple",
    dek: "TTM revenue near ₹2,535 cr; at ₹1,164 base FY27E offers ~8% upside, Neutral on trailing P/E near 76× and ROCE ~7.4%.",
    verdict: "neutral",
    conviction: "medium",
    keyTakeaways: [
      "FY26 revenue ₹2,365 cr; PAT ₹222 cr; OPM 22%; ROCE ~7%.",
      "FY26 net CFO ₹334 cr; borrowings ₹1,867 cr; FCF negative on capex.",
      "Q1 FY27 revenue ₹655 cr; OPM 25%; FY27 guide ₹2,700–2,800 cr.",
      "Base FY27 PAT ₹285 cr × 50× P/E implies ~₹1,252 vs ₹1,164 reference (+8%).",
    ],
    readMinutes: 25,
    publishedAt: "2026-10-04",
    symbol: "ANURAS",
  },
  {
    slug: "alkylamine-midcap-memo",
    title: "Alkyl Amines: integrated amines at a quality multiple after a flat FY26",
    dek: "TTM revenue near ₹1,540 cr; at ₹1,997 base FY27E offers ~5% downside, Neutral on trailing P/E near 45× with net cash.",
    verdict: "neutral",
    conviction: "medium",
    keyTakeaways: [
      "FY26 revenue ₹1,536 cr; PAT ₹180 cr; OPM 19%; ROCE ~14%.",
      "FY26 net CFO ₹225 cr; net cash ~₹40 cr Mar FY26; no leverage.",
      "Q4 FY26 call: FY27 guide 5–10% volume growth; acetonitrile ramp key.",
      "Base FY27 PAT ₹210 cr × 46× P/E implies ~₹1,887 vs ₹1,997 reference (-5%).",
    ],
    readMinutes: 25,
    publishedAt: "2026-10-04",
    symbol: "ALKYLAMINE",
  },
  {
    slug: "balamines-midcap-memo",
    title: "Balaji Amines: methylamine leader in a capex and ROCE trough",
    dek: "TTM revenue near ₹1,523 cr; at ₹2,052 base FY27E offers ~6% upside, Neutral on trailing P/E near 33× and ROCE ~11%.",
    verdict: "neutral",
    conviction: "medium",
    keyTakeaways: [
      "FY26 revenue ₹1,419 cr; PAT ₹169 cr; OPM 19%; ROCE ~11%.",
      "CWIP ₹512 cr; borrowings ₹133 cr; Q1 FY27 OPM 25%.",
      "Q1 FY27 revenue ₹456 cr; PAT ₹78 cr.",
      "Base FY27 PAT ₹228 cr × 31× P/E implies ~₹2,181 vs ₹2,052 reference (+6%).",
    ],
    readMinutes: 25,
    publishedAt: "2026-10-04",
    symbol: "BALAMINES",
  },
  {
    slug: "epigral-midcap-memo",
    title: "Epigral: integrated chlor-alkali at a post-peak earnings multiple",
    dek: "TTM revenue near ₹2,626 cr; at ₹982 base FY27E offers ~6% upside, Neutral on trailing P/E near 16× and ROCE ~15.5%.",
    verdict: "neutral",
    conviction: "medium",
    keyTakeaways: [
      "FY26 revenue ₹2,527 cr; PAT ₹332 cr; OPM 22%; ROCE ~15%.",
      "FY26 net CFO ₹436 cr; borrowings ₹572 cr; CWIP ₹451 cr.",
      "Q1 FY27 revenue ₹705 cr; PAT ₹100 cr; OPM 25%.",
      "Base FY27 PAT ₹280 cr × 16× P/E implies ~₹1,040 vs ₹982 reference (+6%).",
    ],
    readMinutes: 25,
    publishedAt: "2026-10-04",
    symbol: "EPIGRAL",
  },
  {
    slug: "archean-midcap-memo",
    title: "Archean Chemical: bromine cycle trough at a premium earnings multiple",
    dek: "TTM revenue near ₹1,116 cr; at ₹475 base FY27E offers ~2% downside, Neutral on trailing P/E near 61× and ROCE ~7.4%.",
    verdict: "neutral",
    conviction: "medium",
    keyTakeaways: [
      "FY26 revenue ₹1,081 cr; PAT ₹105 cr; OPM 22%; ROCE ~7%.",
      "FY26 net CFO ₹140 cr; borrowings ₹466 cr; CWIP ₹182 cr.",
      "Q1 FY27 revenue ₹327 cr; OPM 21%; TTM PAT ₹96 cr.",
      "Base FY27 PAT ₹115 cr × 50× P/E implies ~₹465 vs ₹475 reference (-2%).",
    ],
    readMinutes: 25,
    publishedAt: "2026-10-04",
    symbol: "ACI",
  },
  {
    slug: "tatvchint-midcap-memo",
    title: "Tatva Chintan: PTC recovery at a premium trailing multiple",
    dek: "TTM revenue near ₹556 cr; at ₹1,743 base FY27E offers ~2% downside, Neutral on trailing P/E near 78× and ROCE ~7.2%.",
    verdict: "neutral",
    conviction: "medium",
    keyTakeaways: [
      "FY26 revenue ₹506 cr; PAT ₹42 cr; OPM 18%; ROCE ~7%.",
      "FY26 net CFO ₹31 cr; borrowings ₹120 cr; FY25 PAT trough ₹6 cr.",
      "Q1 FY27 revenue ₹131 cr; OPM 19%; PAT ₹15 cr (Jun 2026 quarter).",
      "Base FY27 PAT ₹80 cr × 50× P/E implies ~₹1,709 vs ₹1,743 reference (-2%).",
    ],
    readMinutes: 25,
    publishedAt: "2026-10-04",
    symbol: "TATVA",
  },
  {
    slug: "lxchem-midcap-memo",
    title: "Laxmi Organic: Dahej optionality at a spread-inflated trailing multiple",
    dek: "TTM revenue near ₹3,122 cr; at ₹181 base FY27E offers ~8% upside, Neutral on trailing P/E near 40× and ROCE ~4.7%.",
    verdict: "neutral",
    conviction: "medium",
    keyTakeaways: [
      "FY26 revenue ₹2,847 cr; PAT ₹79 cr; OPM 6%; ROCE ~5%.",
      "FY26 net CFO ₹175 cr; borrowings ₹543 cr; CWIP ₹652 cr Mar FY26.",
      "Q1 FY27 revenue ₹968 cr; OPM 12%; PAT ₹68 cr (Jun 2026 quarter).",
      "Base FY27 PAT ₹210 cr × 26× P/E implies ~₹196 vs ₹181 reference (+8%).",
    ],
    readMinutes: 25,
    publishedAt: "2026-10-04",
    symbol: "LXCHEM",
  },
  {
    slug: "jublingrea-midcap-memo",
    title: "Jubilant Ingrevia: pyridine platform at a specialty recovery multiple",
    dek: "TTM revenue near ₹4,651 cr; at ₹638 base FY27E offers ~10% upside, Neutral on trailing P/E near 32× and ROCE ~11.4%.",
    verdict: "neutral",
    conviction: "medium",
    keyTakeaways: [
      "FY26 revenue ₹4,388 cr; PAT ₹278 cr; OPM 13%; ROCE ~11%.",
      "FY26 net CFO ₹524 cr; borrowings ₹792 cr; FCF positive ₹235 cr.",
      "Q1 FY27 revenue ₹1,300 cr; OPM 15%; PAT ₹106 cr (Jun 2026 quarter).",
      "Base FY27 PAT ₹360 cr × 31× P/E implies ~₹701 vs ₹638 reference (+10%).",
    ],
    readMinutes: 25,
    publishedAt: "2026-10-04",
    symbol: "JUBLINGREA",
  },
  {
    slug: "paushak-midcap-memo",
    title: "Paushak: phosgene niche at a post-capex earnings trough",
    dek: "TTM revenue near ₹246 cr; at ₹650 base FY27E offers ~6% upside, Neutral on trailing P/E near 38× and ROCE ~8.3%.",
    verdict: "neutral",
    conviction: "medium",
    keyTakeaways: [
      "FY26 revenue ₹219 cr; PAT ₹39 cr; OPM 28%; ROCE ~8%.",
      "FY26 net CFO ₹54 cr; borrowings ₹77 cr; CWIP ₹26 cr Mar FY26.",
      "Q1 FY27 revenue ₹84 cr; OPM 31%; PAT ₹15 cr (Jun 2026 quarter).",
      "Base FY27 PAT ₹50 cr × 34× P/E implies ~₹688 vs ₹650 reference (+6%).",
    ],
    readMinutes: 25,
    publishedAt: "2026-10-04",
    symbol: "PAUSHAKLTD",
  },
  {
    slug: "privi-midcap-memo",
    title: "Privi Speciality Chemicals: global aroma leader at a premium earnings multiple",
    dek: "TTM revenue near ₹2,671 cr; at ₹3,573 base FY27E offers ~9% upside, Neutral on trailing P/E near 40× and ROCE ~22.3%.",
    verdict: "neutral",
    conviction: "medium",
    keyTakeaways: [
      "FY26 revenue ₹2,564 cr; PAT ₹317 cr; OPM 25%; ROCE ~22%.",
      "FY26 net CFO ₹550 cr; borrowings ₹1,021 cr; FCF positive ₹230 cr.",
      "Q1 FY27 revenue ₹666 cr; OPM 23%; PAT ₹83 cr (Jun 2026 quarter).",
      "Base FY27 PAT ₹400 cr × 38× P/E implies ~₹3,887 vs ₹3,573 reference (+9%).",
    ],
    readMinutes: 25,
    publishedAt: "2026-10-04",
    symbol: "PRIVISCL",
  },
  {
    slug: "chemplast-midcap-memo",
    title: "Chemplast Sanmar: PVC cycle trough with specialty paste resilience",
    dek: "TTM revenue near ₹4,249 cr; at ₹192 base FY27E offers ~7% upside, Neutral on TTM PAT loss and ROCE ~0.3%.",
    verdict: "neutral",
    conviction: "medium",
    keyTakeaways: [
      "FY26 revenue ₹4,249 cr; TTM PAT loss ₹391 cr; OPM ~4%; ROCE ~0.3%.",
      "FY26 net CFO ₹150 cr; borrowings ₹2,450 cr; interest coverage thin.",
      "Q1 FY27 revenue ₹1,050 cr; OPM ~4%; PAT loss ~₹75 cr (Jun 2026 quarter).",
      "Base FY27 PAT ₹170 cr × 19× P/E implies ~₹205 vs ₹192 reference (+7%).",
    ],
    readMinutes: 25,
    publishedAt: "2026-10-04",
    symbol: "CHEMPLASTS",
  },
];
