import type { ArticleBlock } from "./types";

const loaders: Record<string, () => Promise<ArticleBlock[]>> = {
  "fact-midcap-memo": () => import("./content/fact-memo").then((m) => m.factMemoBlocks),
  "chambalfert-midcap-memo": () => import("./content/chambal-memo").then((m) => m.chambalMemoBlocks),
  "coromandel-midcap-memo": () => import("./content/coromandel-memo").then((m) => m.coromandelMemoBlocks),
  "deepakfert-midcap-memo": () => import("./content/deepakfert-memo").then((m) => m.deepakfertMemoBlocks),
  "gnfc-midcap-memo": () => import("./content/gnfc-memo").then((m) => m.gnfcMemoBlocks),
  "gsfc-midcap-memo": () => import("./content/gsfc-memo").then((m) => m.gsfcMemoBlocks),
  "rcf-midcap-memo": () => import("./content/rcf-memo").then((m) => m.rcfMemoBlocks),
  "paradeep-midcap-memo": () => import("./content/paradeep-memo").then((m) => m.paradeepMemoBlocks),
  "mangalorechem-midcap-memo": () => import("./content/mangalorechem-memo").then((m) => m.mangalorechemMemoBlocks),
  "nfl-midcap-memo": () => import("./content/nfl-memo").then((m) => m.nflMemoBlocks),
  "zuariind-midcap-memo": () => import("./content/zuariind-memo").then((m) => m.zuariindMemoBlocks),
  "zuariagro-midcap-memo": () => import("./content/zuariagro-memo").then((m) => m.zuariagroMemoBlocks),
  "piind-midcap-memo": () => import("./content/piind-memo").then((m) => m.piindMemoBlocks),
  "upl-midcap-memo": () => import("./content/upl-memo").then((m) => m.uplMemoBlocks),
  "rallis-midcap-memo": () => import("./content/rallis-memo").then((m) => m.rallisMemoBlocks),
  "dhanuka-midcap-memo": () => import("./content/dhanuka-memo").then((m) => m.dhanukaMemoBlocks),
  "insecticides-midcap-memo": () => import("./content/insecticides-memo").then((m) => m.insecticidesMemoBlocks),
  "sumichem-midcap-memo": () => import("./content/sumichem-memo").then((m) => m.sumichemMemoBlocks),
  "shardacrop-midcap-memo": () => import("./content/shardacrop-memo").then((m) => m.shardacropMemoBlocks),
  "meghmani-midcap-memo": () => import("./content/meghmani-memo").then((m) => m.meghmaniMemoBlocks),
  "bharatras-midcap-memo": () => import("./content/bharatras-memo").then((m) => m.bharatrasMemoBlocks),
  "astec-midcap-memo": () => import("./content/astec-memo").then((m) => m.astecMemoBlocks),
  "heranba-midcap-memo": () => import("./content/heranba-memo").then((m) => m.heranbaMemoBlocks),
  "indofil-midcap-memo": () => import("./content/indofil-memo").then((m) => m.indofilMemoBlocks),
  "naclind-midcap-memo": () => import("./content/naclind-memo").then((m) => m.naclindMemoBlocks),
  "kaveri-midcap-memo": () => import("./content/kaveri-memo").then((m) => m.kaveriMemoBlocks),
  "nathbiogen-midcap-memo": () => import("./content/nathbiogen-memo").then((m) => m.nathbiogenMemoBlocks),
  "aries-midcap-memo": () => import("./content/aries-memo").then((m) => m.ariesMemoBlocks),
  "bhagchem-midcap-memo": () => import("./content/bhagchem-memo").then((m) => m.bhagchemMemoBlocks),
  "bestagro-midcap-memo": () => import("./content/bestagro-memo").then((m) => m.bestagroMemoBlocks),
  "hikal-midcap-memo": () => import("./content/hikal-memo").then((m) => m.hikalMemoBlocks),
  "bhageria-midcap-memo": () => import("./content/bhageria-memo").then((m) => m.bhageriaMemoBlocks),
  "rossari-midcap-memo": () => import("./content/rossari-memo").then((m) => m.rossariMemoBlocks),
  "fineorg-midcap-memo": () => import("./content/fineorg-memo").then((m) => m.fineorgMemoBlocks),
  "galaxysurf-midcap-memo": () => import("./content/galaxysurf-memo").then((m) => m.galaxysurfMemoBlocks),
  "vinatiorga-midcap-memo": () => import("./content/vinatiorga-memo").then((m) => m.vinatiorgaMemoBlocks),
  "cleansci-midcap-memo": () => import("./content/cleansci-memo").then((m) => m.cleansciMemoBlocks),
  "deepaknit-midcap-memo": () => import("./content/deepaknit-memo").then((m) => m.deepaknitMemoBlocks),
  "aartiind-midcap-memo": () => import("./content/aartiind-memo").then((m) => m.aartiindMemoBlocks),
  "atul-midcap-memo": () => import("./content/atul-memo").then((m) => m.atulMemoBlocks),
  "srf-midcap-memo": () => import("./content/srf-memo").then((m) => m.srfMemoBlocks),
  "navinfluor-midcap-memo": () => import("./content/navinfluor-memo").then((m) => m.navinfluorMemoBlocks),
  "fluorochem-midcap-memo": () => import("./content/fluorochem-memo").then((m) => m.fluorochemMemoBlocks),
  "neogen-midcap-memo": () => import("./content/neogen-memo").then((m) => m.neogenMemoBlocks),
  "anupam-midcap-memo": () => import("./content/anupam-memo").then((m) => m.anupamMemoBlocks),
  "alkylamine-midcap-memo": () => import("./content/alkylamine-memo").then((m) => m.alkylamineMemoBlocks),
  "balamines-midcap-memo": () => import("./content/balamines-memo").then((m) => m.balaminesMemoBlocks),
  "epigral-midcap-memo": () => import("./content/epigral-memo").then((m) => m.epigralMemoBlocks),
  "archean-midcap-memo": () => import("./content/archean-memo").then((m) => m.archeanMemoBlocks),
  "tatvchint-midcap-memo": () => import("./content/tatvchint-memo").then((m) => m.tatvchintMemoBlocks),
  "lxchem-midcap-memo": () => import("./content/lxchem-memo").then((m) => m.lxchemMemoBlocks),
  "jublingrea-midcap-memo": () => import("./content/jublingrea-memo").then((m) => m.jublingreaMemoBlocks),
  "paushak-midcap-memo": () => import("./content/paushak-memo").then((m) => m.paushakMemoBlocks),
  "privi-midcap-memo": () => import("./content/privi-memo").then((m) => m.priviMemoBlocks),
  "chemplast-midcap-memo": () => import("./content/chemplast-memo").then((m) => m.chemplastMemoBlocks),
};

export async function loadMemoBlocks(slug: string): Promise<ArticleBlock[] | undefined> {
  const load = loaders[slug];
  if (!load) return undefined;
  return load();
}
